name: image_compare
description: Dart package for image comparison. Compare images for difference using a variety of algorithms.
repository: https://github.com/nitinramadoss/image_compare
version: 1.1.3

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  image: ^4.1.3
  universal_io: ^2.0.0

dev_dependencies:
  lints: ^2.1.1

assets:
  - assets/
  - assets/drawings/
  - assets/animals/
  - assets/objects/
